dist: bionic
language: minimal

git:
  depth: 1

before_script:
  - set -e
  - curl -fsSL -O "https://raw.githubusercontent.com/hoshsadiq/alpine-chroot-install/destroy-script/alpine-chroot-install" # todo checksum this
  - chmod +x alpine-chroot-install

script:
  - ls -la
  - sudo ./make-image
  - ls -la
