dist: bionic
language: minimal

git:
  depth: 1

before_script:
  - set -e
  - curl -fsSL -O "https://raw.githubusercontent.com/hoshsadiq/alpine-chroot-install/destroy-script/alpine-chroot-install" # todo checksum this

script:
  - sudo ./make-image
  - ls -la
