dist: trusty
sudo: required
language: minimal

addons:
  apt:
    packages:
#      - qemu-user-static
#      - binfmt-support
      - docker-ce

services:
  - docker

env:
  global:
    - QUS_VERSION=v4.0.0-4


script:
#  - docker run --rm --privileged multiarch/qemu-user-static:register
  - ls -al /usr/bin/qemu-*
  - ls -al /proc/sys/fs/binfmt_misc/
  - docker run --rm --privileged --entrypoint bash multiarch/qemu-user-static:$QUS_VERSION -xc '/register --reset -p yes'
#  - ls /proc/sys/fs/binfmt_misc
#  - cat /proc/sys/fs/binfmt_misc/*
  - docker run --rm -it -v $(pwd):/workdir arm64v8/alpine:3.10 /workdir/setup
  - ls -la