#!/usr/bin/env sh

set -euxo pipefail

abuild-keygen -i -a -n

curl -fsSL https://github.com/alpinelinux/aports/archive/v3.10.1.tar.gz -o- | tar xzvf - -C /tmp/ aports-3.10.1/scripts aports-3.10.1/main
cd /tmp/aports-3.10.1/scripts
cp /workdir/mkimage.custom.sh .
./mkimage.sh --arch aarch64 \
    --outdir /workdir/build \
    --profile rpi_custom \
    --tag v3.10.1 \
    --repository http://dl-cdn.alpinelinux.org/alpine/v3.10/main \
    --extra-repository http://dl-cdn.alpinelinux.org/alpine/v3.10/community

