#!/usr/bin/env sh

set -euxo pipefail

apk update
apk add --no-progress alpine-sdk \
    build-base \
    apk-tools \
    alpine-conf \
    busybox \
    fakeroot \
    xorriso \
    squashfs-tools

curl -fsSL https://github.com/alpinelinux/aports/archive/v3.10.1.tar.gz -o- \
    | tar xzf - -C /workdir/ aports-3.10.1/scripts aports-3.10.1/main

abuild-keygen -i -a -n

adduser root abuild
su root -c groups

cp /workdir/mkimg.custom.sh /workdir/aports-3.10.1/scripts
/workdir/aports-3.10.1/scripts/mkimage.sh --help || true

su root -c /workdir/mkimage.sh
