#!/usr/bin/env sh

set -euxo pipefail

apk update
apk add --no-progress alpine-sdk \
    build-base \
    apk-tools \
    alpine-conf \
    busybox \
    fakeroot \
    xorriso \
    squashfs-tools

curl -fsSL https://github.com/alpinelinux/aports/archive/v3.10.1.tar.gz -o- \
    | tar xzf - -C /workdir/ aports-3.10.1/scripts aports-3.10.1/main

abuild-keygen -i -a -n

adduser root abuild
su root -c groups

cp /workdir/mkimg.custom.sh /workdir/aports-3.10.1/scripts
/workdir/aports-3.10.1/scripts/mkimage.sh --help || true

su root -c '/workdir/aports-3.10.1/scripts/mkimage.sh \
    --arch aarch64 \
    --outdir /workdir/aports-3.10.1/scripts/build \
    --profile rpi \
    --tag v3.10.1 \
    --repository http://dl-cdn.alpinelinux.org/alpine/v3.10/main \
    --extra-repository http://dl-cdn.alpinelinux.org/alpine/v3.10/community'
