#!/usr/bin/env sh

set -euxo pipefail

apk add --no-cache --no-progress alpine-sdk build-base apk-tools alpine-conf busybox fakeroot xorriso squashfs-tools
curl -fsSL https://github.com/alpinelinux/aports/archive/v3.10.1.tar.gz -o- | tar xzvf - -C /tmp/ aports-3.10.1/scripts aports-3.10.1/main

abuild-keygen -i -a -n


adduser root abuild
su -s /bin/sh root -c groups

cp /workdir/mkimg.custom.sh /tmp/aports-3.10.1/scripts
/tmp/aports-3.10.1/scripts/mkimage.sh --help || true

su -s /bin/sh root -c /tmp/aports-3.10.1/scripts/mkimage.sh --arch aarch64 \
    --outdir /workdir/build \
    --profile rpi_custom \
    --tag v3.10.1 \
    --repository http://dl-cdn.alpinelinux.org/alpine/v3.10/main \
    --extra-repository http://dl-cdn.alpinelinux.org/alpine/v3.10/community
