dist: bionic
language: minimal

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

git:
  depth: 1

env:
  global:
    - QUS_VERSION=v4.0.0-4
  matrix:
    - IMAGE_PREFIX=arm32v6 ARCH=armhf
    - IMAGE_PREFIX=arm64v8 ARCH=aarch64

before_script:
  - set -e
  - docker run --rm --privileged multiarch/qemu-user-static:$QUS_VERSION --reset -p yes

script:
  - docker run --rm -it -v $(pwd):/workdir $IMAGE_PREFIX/alpine:3.10 /workdir/setup
  -

# create image & mount
# extract tar.gz into mount
# release tar.gz + img
# repeat for armhf
