#!/usr/bin/env sh

set -euo pipefail

ARCH=aarch64

/workdir/aports-3.10.1/scripts/mkimage.sh \
    --arch $ARCH \
    --outdir /workdir/aports-3.10.1/scripts/build \
    --profile rpi_custom \
    --tag v3.10.1 \
    --repository http://dl-cdn.alpinelinux.org/alpine/v3.10/main \
    --extra-repository http://dl-cdn.alpinelinux.org/alpine/v3.10/community
